language: python
python:
  - "3.6"
# 安装依赖包的命令
# 这里首先使用pip安装poetry和pytest，然后使用poetry根据配置文件安装
# 也可以全部使用pip安装
install:
    - pip install poetry
    - pip install pytest
    - poetry install
# 这里定义环境变量，用于做ci测试
env:
  - test_run1=test/test_tool1.py
  - test_run2=test/test_tool2.py
# command to run tests
script:
  - pytest $test_run1
  - pytest $test_run2